#!/bin/bash

# uci set wireless.@wifi-device[0].disabled="0"
# uci set wireless.@wifi-device[0].band='5g'
# uci set wireless.@wifi-device[0].country='US'
# uci set wireless.@wifi-device[0].channel='36'
# uci set wireless.@wifi-device[0].htmode='VHT20'
# uci delete wireless.@wifi-device[0].hwmode

# uci set wireless.@wifi-iface[0].disabled="0"
# uci set wireless.@wifi-iface[0].ssid="OpenWrt"
# uci set wireless.@wifi-iface[0].encryption='none'

# uci commit wireless
# wifi reload

uci set network.lan.proto='dhcp'
uci commit network
/etc/init.d/network restart

uci set luci.main.mediaurlbase='/luci-static/argon'
uci commit luci

uci set system.cfg01e48a.zonename='Asia/Shanghai'
uci set system.cfg01e48a.timezone='CST-8'
uci commit system




