#!/bin/sh /etc/rc.common
#
# author: alfred.fu98@gmail.com
#

USE_PROCD=1

START=99
STOP=99

ExecStart="/usr/local/bin/flush_iptable_tproxy"
ExecStop="/usr/local/bin/restore_iptable_tproxy"

start_service() {
    procd_open_instance
    procd_set_param command $ExecStart 
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

start() {
    service_start $ExecStart
}

stop() {
    service_stop $ExecStop
}
