#!/bin/sh /etc/rc.common
#
# author: alfred.fu98@gmail.com
#

USE_PROCD=1

START=99
STOP=99

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

CONF=/usr/local/etc/v2ray/config.json
EXEC=/usr/bin/v2ray

start_service() {
    procd_open_instance
    procd_set_param command $EXEC -config $CONF
    procd_set_param file $CONF
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param env V2RAY_LOCATION_ASSET=/usr/local/share/v2ray
    procd_set_param pidfile /var/run/v2ray.pid
    procd_close_instance
}

start() {
    service_start $EXEC -config $CONF
}

stop() {
    service_stop $EXEC
}

reload() {
    service_reload $EXEC
}
